#lang racket

(provide generatedTMCompiler generatedFCCompiler)

(define generatedTMCompiler
'((read vs0_2)
  (0
   (residual_2 := '((read Right)))
   (states_2 := (list (cons 'initTM vs0_2)))
   (visited_2 := '())
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initTM) 1 86))
  (1
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (2 (redExpr_2 := (reduceExprHash '`(,Left unquote Right) vs_2)) (code_2 := (append code_2 (list (list 'return redExpr_2)))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 3 4))
  (3 (return residual_2))
  (4 (state_2 := (car states_2)) (states_2 := (cdr states_2)) (visited_2 := (cons state_2 visited_2)) (vs_2 := (cdr state_2)) (code_2 := (list state_2)) (pp_2 := (car state_2)) (if (equal? pp_2 'initTM) 5 6))
  (5
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (6 (if (equal? pp_2 'jumpTo_nextLbl) 7 64))
  (7 (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst)))))) (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2)) (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (8 (redExpr_2 := (reduceExprHash '`(,Left unquote Right) vs_2)) (code_2 := (append code_2 (list (list 'return redExpr_2)))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 9 10))
  (9 (return residual_2))
  (10 (state_2 := (car states_2)) (states_2 := (cdr states_2)) (visited_2 := (cons state_2 visited_2)) (vs_2 := (cdr state_2)) (code_2 := (list state_2)) (pp_2 := (car state_2)) (if (equal? pp_2 'initTM) 11 12))
  (11
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (12 (if (equal? pp_2 'jumpTo_nextLbl) 13 14))
  (13
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (14 (if (equal? pp_2 'loopCond) 15 44))
  (15 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (16 (redExpr_2 := (reduceExprHash '`(,Left unquote Right) vs_2)) (code_2 := (append code_2 (list (list 'return redExpr_2)))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 17 18))
  (17 (return residual_2))
  (18 (state_2 := (car states_2)) (states_2 := (cdr states_2)) (visited_2 := (cons state_2 visited_2)) (vs_2 := (cdr state_2)) (code_2 := (list state_2)) (pp_2 := (car state_2)) (if (equal? pp_2 'initTM) 19 20))
  (19
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (20 (if (equal? pp_2 'jumpTo_nextLbl) 21 22))
  (21
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (22 (if (equal? pp_2 'loopCond) 23 24))
  (23 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (24 (return residual_2))
  (25
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr (car progTail))))
   (vs_2 := (modifyState vs_2 'inst valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car inst)))
   (vs_2 := (modifyState vs_2 'instHead valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progTail)))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? instHead 'right)) 26 27))
  (26
   (reducedExprAss_2 := (reduceExprHash '(cons (car Right) Left) vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (reducedExprAss_2 := (reduceExprHash '(cdr Right) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (27 (if (evalWithHashEnv vs_2 '(equal? instHead 'left)) 28 29))
  (28
   (reducedExprAss_2 := (reduceExprHash '(cons (car Left) Right) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (reducedExprAss_2 := (reduceExprHash '(cdr Left) vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (29 (if (evalWithHashEnv vs_2 '(equal? instHead 'goto)) 30 31))
  (30
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'nextLbl valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (31 (if (evalWithHashEnv vs_2 '(equal? instHead 'write)) 32 33))
  (32
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'value valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(cons value (cdr Right)) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (33 (if (evalWithHashEnv vs_2 '(equal? instHead 'if)) 34 43))
  (34
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'condValue valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr (cdr (cdr inst))))))
   (vs_2 := (modifyState vs_2 'nextLbl valueAssignStatic_2))
   (true_state_2 := (cons 'jumpTo_nextLbl vs_2))
   (false_state_2 := (cons 'loopCond vs_2))
   (states_2 := (if (or (member true_state_2 visited_2) (member true_state_2 states_2)) states_2 (cons true_state_2 states_2)))
   (states_2 := (if (or (member false_state_2 visited_2) (member false_state_2 states_2)) states_2 (cons false_state_2 states_2)))
   (reducedExprIf_2 := (reduceExprHash '(equal? condValue (car Right)) vs_2))
   (code_2 := (append code_2 (list (list 'if reducedExprIf_2 true_state_2 false_state_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 35 36))
  (35 (return residual_2))
  (36 (state_2 := (car states_2)) (states_2 := (cdr states_2)) (visited_2 := (cons state_2 visited_2)) (vs_2 := (cdr state_2)) (code_2 := (list state_2)) (pp_2 := (car state_2)) (if (equal? pp_2 'initTM) 37 38))
  (37
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (38 (if (equal? pp_2 'jumpTo_nextLbl) 39 40))
  (39
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (40 (if (equal? pp_2 'loopCond) 41 42))
  (41 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (42 (return residual_2))
  (43 (redExpr_2 := (reduceExprHash '`(,Left unquote Right) vs_2)) (code_2 := (append code_2 (list (list 'return redExpr_2)))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 17 18))
  (44 (return residual_2))
  (45
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr (car progTail))))
   (vs_2 := (modifyState vs_2 'inst valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car inst)))
   (vs_2 := (modifyState vs_2 'instHead valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progTail)))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? instHead 'right)) 46 47))
  (46
   (reducedExprAss_2 := (reduceExprHash '(cons (car Right) Left) vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (reducedExprAss_2 := (reduceExprHash '(cdr Right) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (47 (if (evalWithHashEnv vs_2 '(equal? instHead 'left)) 48 49))
  (48
   (reducedExprAss_2 := (reduceExprHash '(cons (car Left) Right) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (reducedExprAss_2 := (reduceExprHash '(cdr Left) vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (49 (if (evalWithHashEnv vs_2 '(equal? instHead 'goto)) 50 51))
  (50
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'nextLbl valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (51 (if (evalWithHashEnv vs_2 '(equal? instHead 'write)) 52 53))
  (52
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'value valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(cons value (cdr Right)) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (53 (if (evalWithHashEnv vs_2 '(equal? instHead 'if)) 54 63))
  (54
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'condValue valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr (cdr (cdr inst))))))
   (vs_2 := (modifyState vs_2 'nextLbl valueAssignStatic_2))
   (true_state_2 := (cons 'jumpTo_nextLbl vs_2))
   (false_state_2 := (cons 'loopCond vs_2))
   (states_2 := (if (or (member true_state_2 visited_2) (member true_state_2 states_2)) states_2 (cons true_state_2 states_2)))
   (states_2 := (if (or (member false_state_2 visited_2) (member false_state_2 states_2)) states_2 (cons false_state_2 states_2)))
   (reducedExprIf_2 := (reduceExprHash '(equal? condValue (car Right)) vs_2))
   (code_2 := (append code_2 (list (list 'if reducedExprIf_2 true_state_2 false_state_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 55 56))
  (55 (return residual_2))
  (56 (state_2 := (car states_2)) (states_2 := (cdr states_2)) (visited_2 := (cons state_2 visited_2)) (vs_2 := (cdr state_2)) (code_2 := (list state_2)) (pp_2 := (car state_2)) (if (equal? pp_2 'initTM) 57 58))
  (57
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (58 (if (equal? pp_2 'jumpTo_nextLbl) 59 60))
  (59
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (60 (if (equal? pp_2 'loopCond) 61 62))
  (61 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (62 (return residual_2))
  (63 (redExpr_2 := (reduceExprHash '`(,Left unquote Right) vs_2)) (code_2 := (append code_2 (list (list 'return redExpr_2)))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 9 10))
  (64 (if (equal? pp_2 'loopCond) 65 66))
  (65 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (66 (return residual_2))
  (67
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr (car progTail))))
   (vs_2 := (modifyState vs_2 'inst valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car inst)))
   (vs_2 := (modifyState vs_2 'instHead valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progTail)))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? instHead 'right)) 68 69))
  (68
   (reducedExprAss_2 := (reduceExprHash '(cons (car Right) Left) vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (reducedExprAss_2 := (reduceExprHash '(cdr Right) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (69 (if (evalWithHashEnv vs_2 '(equal? instHead 'left)) 70 71))
  (70
   (reducedExprAss_2 := (reduceExprHash '(cons (car Left) Right) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (reducedExprAss_2 := (reduceExprHash '(cdr Left) vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (71 (if (evalWithHashEnv vs_2 '(equal? instHead 'goto)) 72 73))
  (72
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'nextLbl valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (73 (if (evalWithHashEnv vs_2 '(equal? instHead 'write)) 74 75))
  (74
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'value valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(cons value (cdr Right)) vs_2))
   (cmdAssDynamic_2 := (list 'Right ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (75 (if (evalWithHashEnv vs_2 '(equal? instHead 'if)) 76 85))
  (76
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr inst))))
   (vs_2 := (modifyState vs_2 'condValue valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car (cdr (cdr (cdr inst))))))
   (vs_2 := (modifyState vs_2 'nextLbl valueAssignStatic_2))
   (true_state_2 := (cons 'jumpTo_nextLbl vs_2))
   (false_state_2 := (cons 'loopCond vs_2))
   (states_2 := (if (or (member true_state_2 visited_2) (member true_state_2 states_2)) states_2 (cons true_state_2 states_2)))
   (states_2 := (if (or (member false_state_2 visited_2) (member false_state_2 states_2)) states_2 (cons false_state_2 states_2)))
   (reducedExprIf_2 := (reduceExprHash '(equal? condValue (car Right)) vs_2))
   (code_2 := (append code_2 (list (list 'if reducedExprIf_2 true_state_2 false_state_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 77 78))
  (77 (return residual_2))
  (78 (state_2 := (car states_2)) (states_2 := (cdr states_2)) (visited_2 := (cons state_2 visited_2)) (vs_2 := (cdr state_2)) (code_2 := (list state_2)) (pp_2 := (car state_2)) (if (equal? pp_2 'initTM) 79 80))
  (79
   (reducedExprAss_2 := (reduceExprHash ''() vs_2))
   (cmdAssDynamic_2 := (list 'Left ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 'progTM))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 2 67))
  (80 (if (equal? pp_2 'jumpTo_nextLbl) 81 82))
  (81
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (82 (if (equal? pp_2 'loopCond) 83 84))
  (83 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (84 (return residual_2))
  (85 (redExpr_2 := (reduceExprHash '`(,Left unquote Right) vs_2)) (code_2 := (append code_2 (list (list 'return redExpr_2)))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 3 4))
  (86 (if (equal? pp_2 'jumpTo_nextLbl) 87 88))
  (87
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(member nextLbl progTM (lambda (lbl inst) (equal? lbl (car inst))))))
   (vs_2 := (modifyState vs_2 'progTail valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 8 45))
  (88 (if (equal? pp_2 'loopCond) 89 90))
  (89 (if (evalWithHashEnv vs_2 '(equal? (length progTail) 0)) 16 25))
  (90 (return residual_2)))
)

(define generatedFCCompiler
'((read vs0_2)
  (0
   (residual_2 := '((read inp)))
   (states_2 := (list (cons 'initFC vs0_2)))
   (visited_2 := '())
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 1 104))
  (1
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (2 (reduceOtherCmd_2 := (reduceExprHash '(println "Expected goto/if in the end of bb") vs_2)) (code_2 := (append code_2 (list reduceOtherCmd_2))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 3 4))
  (3 (return residual_2))
  (4
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 5 6))
  (5
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (6 (if (equal? pp_2 'process_if_true) 7 76))
  (7
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (8 (reduceOtherCmd_2 := (reduceExprHash '(println "Expected goto/if in the end of bb") vs_2)) (code_2 := (append code_2 (list reduceOtherCmd_2))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 9 10))
  (9 (return residual_2))
  (10
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 11 12))
  (11
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (12 (if (equal? pp_2 'process_if_true) 13 14))
  (13
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (14 (if (equal? pp_2 'process_if_false) 15 50))
  (15
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (16 (reduceOtherCmd_2 := (reduceExprHash '(println "Expected goto/if in the end of bb") vs_2)) (code_2 := (append code_2 (list reduceOtherCmd_2))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 17 18))
  (17 (return residual_2))
  (18
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 19 20))
  (19
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (20 (if (equal? pp_2 'process_if_true) 21 22))
  (21
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (22 (if (equal? pp_2 'process_if_false) 23 24))
  (23
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (24 (return residual_2))
  (25
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car insts)))
   (vs_2 := (modifyState vs_2 'inst valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr insts)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (car inst) 'if)) 26 35))
  (26
   (true_state_2 := (cons 'process_if_true vs_2))
   (false_state_2 := (cons 'process_if_false vs_2))
   (states_2 := (if (or (member true_state_2 visited_2) (member true_state_2 states_2)) states_2 (cons true_state_2 states_2)))
   (states_2 := (if (or (member false_state_2 visited_2) (member false_state_2 states_2)) states_2 (cons false_state_2 states_2)))
   (reducedExprIf_2 := (reduceExprHash '(evalWithEnv st (cadr inst)) vs_2))
   (code_2 := (append code_2 (list (list 'if reducedExprIf_2 true_state_2 false_state_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 27 28))
  (27 (return residual_2))
  (28
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 29 30))
  (29
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (30 (if (equal? pp_2 'process_if_true) 31 32))
  (31
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (32 (if (equal? pp_2 'process_if_false) 33 34))
  (33
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (34 (return residual_2))
  (35 (if (evalWithHashEnv vs_2 '(equal? (cadr inst) ':=)) 36 37))
  (36
   (reducedExprAss_2 := (reduceExprHash '(changeSt st (car inst) (evalWithEnv st (caddr inst))) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (37 (if (evalWithHashEnv vs_2 '(equal? (car inst) 'goto)) 38 39))
  (38
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (39 (if (evalWithHashEnv vs_2 '(equal? (car inst) 'return)) 40 49))
  (40
   (reducedExprAss_2 := (reduceExprHash '(evalWithEnv st (cadr inst)) vs_2))
   (cmdAssDynamic_2 := (list 'result ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (redExpr_2 := (reduceExprHash 'result vs_2))
   (code_2 := (append code_2 (list (list 'return redExpr_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 41 42))
  (41 (return residual_2))
  (42
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 43 44))
  (43
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (44 (if (equal? pp_2 'process_if_true) 45 46))
  (45
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (46 (if (equal? pp_2 'process_if_false) 47 48))
  (47
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (48 (return residual_2))
  (49 (reduceOtherCmd_2 := (reduceExprHash '(println "Expected goto/if in the end of bb") vs_2)) (code_2 := (append code_2 (list reduceOtherCmd_2))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 17 18))
  (50 (return residual_2))
  (51
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car insts)))
   (vs_2 := (modifyState vs_2 'inst valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr insts)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (car inst) 'if)) 52 61))
  (52
   (true_state_2 := (cons 'process_if_true vs_2))
   (false_state_2 := (cons 'process_if_false vs_2))
   (states_2 := (if (or (member true_state_2 visited_2) (member true_state_2 states_2)) states_2 (cons true_state_2 states_2)))
   (states_2 := (if (or (member false_state_2 visited_2) (member false_state_2 states_2)) states_2 (cons false_state_2 states_2)))
   (reducedExprIf_2 := (reduceExprHash '(evalWithEnv st (cadr inst)) vs_2))
   (code_2 := (append code_2 (list (list 'if reducedExprIf_2 true_state_2 false_state_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 53 54))
  (53 (return residual_2))
  (54
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 55 56))
  (55
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (56 (if (equal? pp_2 'process_if_true) 57 58))
  (57
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (58 (if (equal? pp_2 'process_if_false) 59 60))
  (59
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (60 (return residual_2))
  (61 (if (evalWithHashEnv vs_2 '(equal? (cadr inst) ':=)) 62 63))
  (62
   (reducedExprAss_2 := (reduceExprHash '(changeSt st (car inst) (evalWithEnv st (caddr inst))) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (63 (if (evalWithHashEnv vs_2 '(equal? (car inst) 'goto)) 64 65))
  (64
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (65 (if (evalWithHashEnv vs_2 '(equal? (car inst) 'return)) 66 75))
  (66
   (reducedExprAss_2 := (reduceExprHash '(evalWithEnv st (cadr inst)) vs_2))
   (cmdAssDynamic_2 := (list 'result ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (redExpr_2 := (reduceExprHash 'result vs_2))
   (code_2 := (append code_2 (list (list 'return redExpr_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 67 68))
  (67 (return residual_2))
  (68
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 69 70))
  (69
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (70 (if (equal? pp_2 'process_if_true) 71 72))
  (71
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (72 (if (equal? pp_2 'process_if_false) 73 74))
  (73
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (74 (return residual_2))
  (75 (reduceOtherCmd_2 := (reduceExprHash '(println "Expected goto/if in the end of bb") vs_2)) (code_2 := (append code_2 (list reduceOtherCmd_2))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 9 10))
  (76 (if (equal? pp_2 'process_if_false) 77 78))
  (77
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (78 (return residual_2))
  (79
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car insts)))
   (vs_2 := (modifyState vs_2 'inst valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr insts)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(equal? (car inst) 'if)) 80 89))
  (80
   (true_state_2 := (cons 'process_if_true vs_2))
   (false_state_2 := (cons 'process_if_false vs_2))
   (states_2 := (if (or (member true_state_2 visited_2) (member true_state_2 states_2)) states_2 (cons true_state_2 states_2)))
   (states_2 := (if (or (member false_state_2 visited_2) (member false_state_2 states_2)) states_2 (cons false_state_2 states_2)))
   (reducedExprIf_2 := (reduceExprHash '(evalWithEnv st (cadr inst)) vs_2))
   (code_2 := (append code_2 (list (list 'if reducedExprIf_2 true_state_2 false_state_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 81 82))
  (81 (return residual_2))
  (82
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 83 84))
  (83
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (84 (if (equal? pp_2 'process_if_true) 85 86))
  (85
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (86 (if (equal? pp_2 'process_if_false) 87 88))
  (87
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (88 (return residual_2))
  (89 (if (evalWithHashEnv vs_2 '(equal? (cadr inst) ':=)) 90 91))
  (90
   (reducedExprAss_2 := (reduceExprHash '(changeSt st (car inst) (evalWithEnv st (caddr inst))) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (91 (if (evalWithHashEnv vs_2 '(equal? (car inst) 'goto)) 92 93))
  (92
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (93 (if (evalWithHashEnv vs_2 '(equal? (car inst) 'return)) 94 103))
  (94
   (reducedExprAss_2 := (reduceExprHash '(evalWithEnv st (cadr inst)) vs_2))
   (cmdAssDynamic_2 := (list 'result ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (redExpr_2 := (reduceExprHash 'result vs_2))
   (code_2 := (append code_2 (list (list 'return redExpr_2))))
   (residual_2 := (append residual_2 (list code_2)))
   (if (null? states_2) 95 96))
  (95 (return residual_2))
  (96
   (println (list 'visited_2 'length: (length visited_2)))
   (state_2 := (car states_2))
   (states_2 := (cdr states_2))
   (visited_2 := (cons state_2 visited_2))
   (vs_2 := (cdr state_2))
   (code_2 := (list state_2))
   (pp_2 := (car state_2))
   (if (equal? pp_2 'initFC) 97 98))
  (97
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car progFC)))
   (vs_2 := (modifyState vs_2 'head valueAssignStatic_2))
   (reducedExprAss_2 := (reduceExprHash '(makeSt head inp) vs_2))
   (cmdAssDynamic_2 := (list 'st ':= reducedExprAss_2))
   (code_2 := (append code_2 (list cmdAssDynamic_2)))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr progFC)))
   (vs_2 := (modifyState vs_2 'blocks valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(car blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 2 79))
  (98 (if (equal? pp_2 'process_if_true) 99 100))
  (99
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (100 (if (equal? pp_2 'process_if_false) 101 102))
  (101
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (102 (return residual_2))
  (103 (reduceOtherCmd_2 := (reduceExprHash '(println "Expected goto/if in the end of bb") vs_2)) (code_2 := (append code_2 (list reduceOtherCmd_2))) (residual_2 := (append residual_2 (list code_2))) (if (null? states_2) 3 4))
  (104 (if (equal? pp_2 'process_if_true) 105 106))
  (105
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (caddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 8 51))
  (106 (if (equal? pp_2 'process_if_false) 107 108))
  (107
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(assoc (cadddr inst) blocks)))
   (vs_2 := (modifyState vs_2 'bb valueAssignStatic_2))
   (valueAssignStatic_2 := (evalWithHashEnv vs_2 '(cdr bb)))
   (vs_2 := (modifyState vs_2 'insts valueAssignStatic_2))
   (if (evalWithHashEnv vs_2 '(empty? insts)) 16 25))
  (108 (return residual_2)))
)